events {
    worker_connections 1024;
}

http {
    # upstream nomeUsadoaquiDentro
    upstream apiapi {
        # server nomeApi:portaDeDentro
        server api1:5678;
        server api2:5678;
        server api3:5678;
    }

    server {
        # listen portaOndeVaiRodar
        listen 80;
        location /api {
            proxy_pass http://apiapi;
        }
    }
}