events {
    worker_connections 1024;
}
http {
    upstream iagroapi{
        server api:5215;
    }

    server{
        listen 1018;
        location /api {
            proxy_pass http://iagroapi;
        }
    }
}

